# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fantope Projection and Selection
#'
#' This function computes a solution path of the Fantope Projection and
#' Selection (FPS) estimator.  It takes a symmetric matrix \code{S} as input 
#' and returns an object containing a list of projection matrices 
#' estimated by FPS over a sequence of regularization parameter values.
#'
#' By default, a sensible minimum value of the regularization parameter 
#' is automatically chosen so that the minimally regularized solution
#' is different from PCA.
#'
#' @param S              Input matrix (assumed to be symmetric)
#' @param ndim           Target subspace dimension (can be fractional)
#' @param nsol           Number of solutions to compute
#' @param lambda         Vector of regularization parameter values
#' @param lambdamin      Minimum value of lambda (automatic if < 0)
#' @param maxnvar        Suggested maximum number of variables to include 
#'                       (ignored if <= 0)
#' @param maxiter        Maximum number of iterations for each solution
#' @param tolerance      Convergence threshold
#' @param verbose        Level of verbosity (0 = silent, >0 = increasing 
#'                       verbosity)
#'
#' @return Object of class 'fps'
#'
#' @export
#'
#' @examples
#' # Apply FPS to the standardized wine data from the UCI ML repository
#' data(wine)
#' out <- fps(cor(wine), ndim = 2)
#' print(out)
#' plot(out)
#'
#' # Create a synthetic dataset by adding noise variables to the wine data
#' j <- sample(1:ncol(wine), size = 500 - ncol(wine), replace = TRUE)
#' noise <- apply(wine[, j], 2, sample, replace = TRUE)
#' colnames(noise) <- rep('noise', ncol(noise))
#' x <- cbind(wine, noise)
#' out <- fps(cor(x), ndim = 2, verbose = 1)
#'
#' # Choose lambda by cross-validation (this may take a few minutes)
#' \dontrun{
#' cvout <- cv(out, x, FUN = cor, verbose = 1)
#' plot(cvout)
#' v <- coef(out, lambda = cvout$lambda.cv)
#' print(v)
#' }
#'
fps <- function(S, ndim, lambda = as.numeric( c()), nsol = 50L, lambdamin = -1, maxnvar = -1L, maxiter = 100L, tolerance = 1e-3, verbose = 0L) {
    .Call('fps_fps', PACKAGE = 'fps', S, ndim, lambda, nsol, lambdamin, maxnvar, maxiter, tolerance, verbose)
}

